name: uix
version: 0.5.1
author: Boris Kaul <localvoid@gmail.com>
description: Library to build Web User Interfaces inspired by React.
homepage: https://github.com/localvoid/uix
environment:
  sdk: '>=1.9.1'
dependencies:
  collection: '^1.1.0'
dev_dependencies:
  browser: any
  unittest: '<0.12.0'
